### ISSUE TITLE
sharp ERROR

### ISSUE THREAD

**Issue by ravindu01manoj** [AlenSaito1/wa-sticker-formatter#27]
]: /root/QueenSewWhatsappBot/node_modules/sharp/lib/sharp.js:30
2021-11-19T09:44:22.947378+00:00 app[worker.1]:   throw new Error(help.join('\n'));
2021-11-19T09:44:22.947379+00:00 app[worker.1]:         ^
2021-11-19T09:44:22.947379+00:00 app[worker.1]: 
2021-11-19T09:44:22.947380+00:00 app[worker.1]: Error: 
2021-11-19T09:44:22.947380+00:00 app[worker.1]: Something went wrong installing the "sharp" module
2021-11-19T09:44:22.947380+00:00 app[worker.1]: 
2021-11-19T09:44:22.947382+00:00 app[worker.1]: Error relocating /root/QueenSewWhatsappBot/node_modules/sharp/build/Release/../.././vendor/8.11.3/linuxmusl-x64/lib/libvips-cpp.so.42: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
2021-11-19T09:44:22.947382+00:00 app[worker.1]:

**Comment by AlenSaito1** [comment]
These logs are not enough, could you give a bit more context?

**Comment by ravindu01manoj** [comment]
okey wait

**Comment by ravindu01manoj** [comment]
2021-11-19T10:34:44.444649+00:00 app[worker.1]: /root/QueenSewWhatsappBot/node_modules/sharp/lib/constructor.js:32
2021-11-19T10:34:44.444658+00:00 app[worker.1]:   throw new Error(error);
2021-11-19T10:34:44.444659+00:00 app[worker.1]:         ^
2021-11-19T10:34:44.444659+00:00 app[worker.1]: 
2021-11-19T10:34:44.444659+00:00 app[worker.1]: Error: 
2021-11-19T10:34:44.444660+00:00 app[worker.1]: Something went wrong installing the "sharp" module
2021-11-19T10:34:44.444660+00:00 app[worker.1]: 
2021-11-19T10:34:44.444661+00:00 app[worker.1]: Error relocating /root/QueenSewWhatsappBot/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/libvips-cpp.so.42: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
2021-11-19T10:34:44.444661+00:00 app[worker.1]: 
2021-11-19T10:34:44.444662+00:00 app[worker.1]: - Remove the "node_modules/sharp" directory then run
2021-11-19T10:34:44.444662+00:00 app[worker.1]:   "npm install --ignore-scripts=false --verbose sharp" and look for errors
2021-11-19T10:34:44.444663+00:00 app[worker.1]: - Consult the installation documentation at https://sharp.pixelplumbing.com/install
2021-11-19T10:34:44.444663+00:00 app[worker.1]: - Search for this error at https://github.com/lovell/sharp/issues
2021-11-19T10:34:44.444663+00:00 app[worker.1]: 
2021-11-19T10:34:44.444664+00:00 app[worker.1]:     at Object.<anonymous> (/root/QueenSewWhatsappBot/node_modules/sharp/lib/constructor.js:32:9)
2021-11-19T10:34:44.444664+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1102:14)
2021-11-19T10:34:44.444665+00:00 app[worker.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
2021-11-19T10:34:44.444665+00:00 app[worker.1]:     at Module.load (node:internal/modules/cjs/loader:967:32)
2021-11-19T10:34:44.444666+00:00 app[worker.1]:     at Function.Module._load (node:internal/modules/cjs/loader:807:14)
2021-11-19T10:34:44.444666+00:00 app[worker.1]:     at Module.require (node:internal/modules/cjs/loader:991:19)
2021-11-19T10:34:44.444666+00:00 app[worker.1]:     at require (node:internal/modules/cjs/helpers:92:18)
2021-11-19T10:34:44.444667+00:00 app[worker.1]:     at Object.<anonymous> (/root/QueenSewWhatsappBot/node_modules/sharp/lib/index.js:3:15)
2021-11-19T10:34:44.444667+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1102:14)
2021-11-19T10:34:44.444667+00:00 app[worker.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)

**Comment by ravindu01manoj** [comment]
any solution ???..i need this npm soonly 💖

**Comment by AlenSaito1** [comment]
Looks like you're in a Heroku Environment. Does the same error occur locally?

**Comment by evaasmakula** [comment]
> Looks like you're in a Heroku Environment. Does the same error occur locally?

it happend in termux too

**Comment by AlenSaito1** [comment]
@evaasmakula have you tried the solutions mentioned here? https://github.com/lovell/sharp/issues/1889
