### ISSUE TITLE
Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by Gimenz** [AlenSaito1/wa-sticker-formatter#33]
i try to extractMetadata a sticker without packname and author , but it says error like this 

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at C:\Users\Administrator\nganu\node_modules\wa-sticker-formatter\dist\extractMetadata.js:22:27
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Administrator\nganu\node_modules\wa-sticker-formatter\dist\extractMetadata.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

can we handle this with empty result, like 
```
{
    'emojis': [],
    'sticker-pack-id': '',
    'sticker-pack-name': '',
    'sticker-pack-publisher': '',
}
```

sorry for my bad english 😄

**Comment by Gimenz** [comment]
ah, big thnks bro.
